export enum EQUERY_PARAMTER_ACTIONS {
  OPEN = "OPEN",
}

export enum EQUERY_PARAMTER_VALUES {
  ADD_CARD = "ADD_CARD",
  CHARGE_WALLET = "CHARGE_WALLET",
  LOGIN = "LOGIN",
  LOGIN_FD = "LOGIN_FD",
  REGISTER = "REGISTER",
  FORGET_PASSWORD = "FORGET_PASSWORD",
}
