export enum ETransactionType {
  TOPUP_WALLET = "TOPUP_WALLET",
  OPPORTUNITY_INVEST = "OPPORTUNITY_INVEST",
  OPPORTUNITY_BUY_PERK = "OPPORTUNITY_BUY_PERK",
  CANCEL_BUY_PERK = "CANCEL_BUY_PERK",
  OPPORTUNITY_INVEST_tx_FEES = "OPPORTUNITY_INVEST_tx_FEES",
  TRANSFER_FUNDS_FROM_OPPORTUNITY_TO_MANAGER = "TRANSFER_FUNDS_FROM_OPPORTUNITY_TO_MANAGER",
  TRANSFER_FUNDS_FROM_MANAGER_TO_OPPORTUNITY = "TRANSFER_FUNDS_FROM_MANAGER_TO_OPPORTUNITY",
  WITHDRAW = "WITHDRAW",
  DISTRIBUTED_FINAL_FUNDS = "DISTRIBUTED_FINAL_FUNDS",
  DISTRIBUTED_DIVIDENDS_FUNDS = "DISTRIBUTED_DIVIDENDS_FUNDS",
}

export enum ETransactionTopupSource {
  BANK_TRANSFER = "BANK_TRANSFER",
  CARD = "CARD",
}

export enum ETransactionStatus {
  PROCESSED = "PROCESSED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  PENDING_APPROVAL_APPROVED = "PENDING_APPROVAL_APPROVED",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
  PENDING_APPROVAL_REJECTED = "PENDING_APPROVAL_REJECTED",
  TMP = "TMP",
  TMP_DONE = "TMP_DONE",
  TMP_DONE_SUCCESS = "TMP_DONE_SUCCESS",
  TMP_DONE_ERROR = "TMP_DONE_ERROR",
}

export enum ETransactionPrtType {
  CREDIT = "CREDIT",
  DEBIT = "DEBIT",
}
